services:
  AbioticFactorServer:
    image: mber1991/abioticfactor-server
    restart: no
    environment:
      - SERVERPASSWORD=test
    ports:
      - "0.0.0.0:7777:7777/udp"
      - "0.0.0.0:27015:27015/udp"
    networks:
      - bridge
    volumes:
      - "./data:/server/AbioticFactor/Saved/SaveGames/Server"

networks:
  bridge:
    driver: bridge