services:
  AbioticFactorServer:
    image: mber1991/abioticfactor-server
    restart: no
    environment:
      - SERVERPASSWORD=test
    ports:
      - "0.0.0.0:7777:7777/udp"
      - "0.0.0.0:27015:27015/udp"
    networks:
      - bridge
    volumes:
      - "./data:/server/AbioticFactor/Saved/SaveGames/Server"

networks:
  bridge:
    driver: bridge

    #volumes:
    #- /your/storage/path/:/data # where transmission will store the data
    #- /your/config/path/:/config # where transmission-home is stored
    #environment:
    #  - OPENVPN_PROVIDER=PIA
    #  - OPENVPN_USERNAME=username
    #  - OPENVPN_PASSWORD=password
    #  - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    #  - LOCAL_NETWORK=192.168.0.0/24
