services:
  AbioticFactorServer:
    image: mber1991/abioticfactor-server
    stop_grace_period: 1m
    restart: no
    init: true
    #env_file: # Create a .env file and specify SERVERPASSWORD
    #  - .env
    #environment:
    #  - SERVERNAME=CHANGEME!
    #  - WORLDSAVENAME=CHANGEME!
    #  - MAXPLAYERS=CHANGEME!
    ports:
      - "0.0.0.0:7777:7777/udp"
      - "0.0.0.0:27015:27015/udp"
    networks:
      - bridge
    volumes:
      - ./config:/config
      - abioticfactor:/server/AbioticFactor/Saved:rw # DO NOT USE A LOCAL MOUNT IT CORRUPTS WORLD SAVES

networks:
  bridge:
    driver: bridge

volumes:
  abioticfactor: